version: '3.7'

services:
  web:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  cms:
    image: node:18-alpine
    working_dir: /app/cms
    volumes:
      - ./cms:/app/cms
      - /app/cms/node_modules
    command: npm run dev
    ports:
      - '3001:3000'
    environment:
      - PAYLOAD_SECRET=your_secret
      - MONGODB_URI=mongodb://mongodb:27017/payload
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db



version: '3.7'

services:
  web:
    build:
      context: ./src/app
    ports:
      - '3000:3000'
    volumes:
      - ./src/app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/payload
      - PAYLOAD_SECRET=your_secret
      - PAYLOAD_PUBLIC_BASE_URL=http://localhost:3000
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost:3001/graphql
    depends_on:
      - db
      - cms

  cms:
    build:
      context: ./src/cms
    ports:
      - '3001:3000'
    volumes:
      - ./src/cms:/app/cms
      - /app/cms/node_modules
    environment:
      - NODE_ENV=development
      - PAYLOAD_SECRET=your_secret
      # - MONGODB_URI=mongodb://db:27017/payload
      - PAYLOAD_PUBLIC_BASE_URL=http://localhost:3001
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: payload
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
